// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: storage.proto

package storage

import (
	notification "github.com/artlink52/notification-system/pkg/pb/notification"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveNotificationRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	UserId        int64                           `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Type          notification.NotificationType   `protobuf:"varint,3,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
	Status        notification.NotificationStatus `protobuf:"varint,4,opt,name=status,proto3,enum=notification.NotificationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveNotificationRequest) Reset() {
	*x = SaveNotificationRequest{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveNotificationRequest) ProtoMessage() {}

func (x *SaveNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveNotificationRequest.ProtoReflect.Descriptor instead.
func (*SaveNotificationRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *SaveNotificationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SaveNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SaveNotificationRequest) GetType() notification.NotificationType {
	if x != nil {
		return x.Type
	}
	return notification.NotificationType(0)
}

func (x *SaveNotificationRequest) GetStatus() notification.NotificationStatus {
	if x != nil {
		return x.Status
	}
	return notification.NotificationStatus(0)
}

type SaveNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveNotificationResponse) Reset() {
	*x = SaveNotificationResponse{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveNotificationResponse) ProtoMessage() {}

func (x *SaveNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveNotificationResponse.ProtoReflect.Descriptor instead.
func (*SaveNotificationResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *SaveNotificationResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GetNotificationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetNotificationResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Id            int64                           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                           `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                          `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Type          notification.NotificationType   `protobuf:"varint,4,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
	Status        notification.NotificationStatus `protobuf:"varint,5,opt,name=status,proto3,enum=notification.NotificationStatus" json:"status,omitempty"`
	CreatedAt     string                          `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RetryCount    int32                           `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationResponse) Reset() {
	*x = GetNotificationResponse{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationResponse) ProtoMessage() {}

func (x *GetNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetNotificationResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetNotificationResponse) GetType() notification.NotificationType {
	if x != nil {
		return x.Type
	}
	return notification.NotificationType(0)
}

func (x *GetNotificationResponse) GetStatus() notification.NotificationStatus {
	if x != nil {
		return x.Status
	}
	return notification.NotificationStatus(0)
}

func (x *GetNotificationResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetNotificationResponse) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\astorage\x1a\x12notification.proto\"\xba\x01\n" +
	"\x17SaveNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.notification.NotificationTypeR\x04type\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2 .notification.NotificationStatusR\x06status\"*\n" +
	"\x18SaveNotificationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"(\n" +
	"\x16GetNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8a\x02\n" +
	"\x17GetNotificationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x122\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1e.notification.NotificationTypeR\x04type\x128\n" +
	"\x06status\x18\x05 \x01(\x0e2 .notification.NotificationStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount2\xbf\x01\n" +
	"\x0eStorageService\x12W\n" +
	"\x10SaveNotification\x12 .storage.SaveNotificationRequest\x1a!.storage.SaveNotificationResponse\x12T\n" +
	"\x0fGetNotification\x12\x1f.storage.GetNotificationRequest\x1a .storage.GetNotificationResponseBAZ?github.com/artlink52/notification-system/pkg/pb/storage;storageb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storage_proto_goTypes = []any{
	(*SaveNotificationRequest)(nil),      // 0: storage.SaveNotificationRequest
	(*SaveNotificationResponse)(nil),     // 1: storage.SaveNotificationResponse
	(*GetNotificationRequest)(nil),       // 2: storage.GetNotificationRequest
	(*GetNotificationResponse)(nil),      // 3: storage.GetNotificationResponse
	(notification.NotificationType)(0),   // 4: notification.NotificationType
	(notification.NotificationStatus)(0), // 5: notification.NotificationStatus
}
var file_storage_proto_depIdxs = []int32{
	4, // 0: storage.SaveNotificationRequest.type:type_name -> notification.NotificationType
	5, // 1: storage.SaveNotificationRequest.status:type_name -> notification.NotificationStatus
	4, // 2: storage.GetNotificationResponse.type:type_name -> notification.NotificationType
	5, // 3: storage.GetNotificationResponse.status:type_name -> notification.NotificationStatus
	0, // 4: storage.StorageService.SaveNotification:input_type -> storage.SaveNotificationRequest
	2, // 5: storage.StorageService.GetNotification:input_type -> storage.GetNotificationRequest
	1, // 6: storage.StorageService.SaveNotification:output_type -> storage.SaveNotificationResponse
	3, // 7: storage.StorageService.GetNotification:output_type -> storage.GetNotificationResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
